# Generated by Django 3.1.1 on 2020-10-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0002_cheese_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheese',
            old_name='country',
            new_name='country_of_origin',
        ),
    ]
